version: '3.8'

services:
  fixly-db:
    image: mysql:8.0
    container_name: fixly-db

    environment:
      MYSQL_DATABASE: fixly
      MYSQL_USER: fixly
      MYSQL_PASSWORD: fixly123
      MYSQL_ROOT_PASSWORD: root123
      # Optimizations for development
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
      MYSQL_INNODB_LOG_FILE_SIZE: 64M

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - fixly-network

    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1
      --max_connections=200

  fixly-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fixly-app

    ports:
      - "8000:8000"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8000

      SPRING_DATASOURCE_URL: jdbc:mysql://fixly-db:3306/fixly?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: fixly
      SPRING_DATASOURCE_PASSWORD: fixly123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

      JWT_SECRET_KEY: Prod_Fixly_2025_Super_Secret_Key_With_Special_Chars_!@
      JWT_EXPIRATION: 1800000

      CLOUDINARY_CLOUD_NAME: dzemlz1jb
      CLOUDINARY_API_KEY: 697511796148143
      CLOUDINARY_API_SECRET: 2GXtOlARXsy-rSOVV2TkqMYTT3Q

      LOGGING_LEVEL_COM_FEMCODERS_FIXLY: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG

    restart: unless-stopped

    depends_on:
      fixly-db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

    networks:
      - fixly-network

    volumes:
      - app_logs:/app/logs

networks:
  fixly-network:
    driver: bridge
    name: fixly-network

volumes:
  mysql_data:
    name: fixly_mysql_data
  app_logs:
    name: fixly_app_logs