spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: fixly
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop  #update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

server:
  port: ${SERVER_PORT:8080}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret-key: ${JWT_SECRET_KEY:Rml4bHlBcHBsaWNhdGlvblNlY3VyZUpXVFNlY3JldEtleTIwMjVGZW1Db2RlcnM=}
  expiration: ${JWT_EXPIRATION:1800000}